<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\MelonLoader\**\*.dll" Private="false" />
		<None Remove="assets\fbt" />
		<EmbeddedResource Include="assets\fbt" />
		<PackageReference Include="BuildSoft.OscCore" Version="1.2.1.1" />
		<Reference Include="ReplayMod">
		  <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RUMBLE\Mods\ReplayMod.dll</HintPath>
		</Reference>
		<Reference Include="UIFramework">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\Mods\UIFramework.dll</HintPath>
		</Reference>
		<Reference Include="RumbleModdingAPI">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\Mods\RumbleModdingAPI.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy &quot;$(TargetPath)&quot; &quot;C:\Program Files (x86)\Steam\steamapps\common\RUMBLE\Mods\$(TargetFileName)&quot;" />
	</Target>

</Project>